name: jobs examples
on:
    push      
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: criando um artefato para reuso
              run: echo "Full featured artifact" > build-result.txt
    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: usar o artefato criado anteriormente
              run: ls build-result.txt
