name: jobs examples
on:
    push      
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: criando um artefato para reuso (changed)
              run: echo "Full featured artifact" > build-result.txt
            - uses: actions/upload-artifact@v2
              with:
                name: build-result
                path: build-result.txt
    deploy:
        if: "contains(github.event.head_commit.message, '[deploy]')"
        runs-on: ubuntu-latest
        needs: build
        steps:
            - uses: actions/download-artifact@v2
              with:
                name: build-result
                path: build-result.txt
            - name: usar o artefato criado anteriormente
              run: ls build-result.txt
